/* Autogenerated by png2wx.pl on Sun Nov  1 12:38:30 2020 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_Openwaterkaart;
extern wxBitmap *_img_Openwaterkaart_pi;

#endif /* ICONS_H */
