/* Autogenerated by png2wx.pl on Mon Dec 21 17:09:15 2020 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_Openwaterkaart;
extern wxBitmap *_img_Openwaterkaart_pi;

#endif /* ICONS_H */
